name: Gitleaks Scanner
on:
  workflow_call:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Security
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
