name: Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Security
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c 7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t viniciuspoa2/nlwunite_backend:${{ github.run_number }} .

      - name: Login container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  # scan:
  #   name: Image Scanner
  #   needs: [build-and-push]
  #   uses: RxJSVini/aws-ecs-fargate-ecs/.github/workflows/scan.yml@main
  #   with:
  #     docker_image: viniciuspoa2/nlwunite_backend:${{ github.run_number }}
