name: Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Security
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c 7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t viniciuspoa2/nlwunite_backend:${{ steps.generate_sha.outputs.sha }} .

      - name: Login container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set Docker Image Environment Variable
        run: echo "DOCKER_IMAGE=viniciuspoa2/nlwunite_backend:${{ steps.generate_sha.outputs.sha }}" >> $GITHUB_ENV
        

  scan:
    name: Image Scanner
    uses: RxJSVini/aws-ecs-fargate-ecs/.github/workflows/scan.yml@main
    needs: [build-and-push]
    with:
      docker_image: ${{ env.DOCKER_IMAGE }}